# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('PSE', 'PSE'), ('CC', 'Crédito')], max_length=10)),
                ('card_type', models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('diners', 'Diners')], max_length=25)),
                ('transaction_id', models.CharField(max_length=150)),
                ('last_four_digits', models.CharField(max_length=5)),
            ],
        ),
    ]
