# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 02:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type', models.CharField(blank=True, choices=[('trulii', 'Comisión Trulii'), ('iva', 'IVA'), ('payu_fee_percentage', 'Comisión PayU porcentual'), ('payu_fee_fixed', 'Comisión PayU fija'), ('renta', 'Descuento de Retención Renta'), ('ica', 'Descuento de Retención ICA'), ('iva_trulii_payu', 'Comisión PayU IVA Trulii'), ('reteica_num', 'Reteica Numerador'), ('reteica_den', 'Reteica Denominador'), ('reteiva', 'Reteiva')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('PSE', 'PSE'), ('CC', 'Crédito')], max_length=10)),
                ('card_type', models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('diners', 'Diners')], max_length=25)),
                ('transaction_id', models.CharField(max_length=150)),
                ('last_four_digits', models.CharField(max_length=5)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
