# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='name',
        ),
        migrations.AddField(
            model_name='fee',
            name='type',
            field=models.CharField(blank=True, choices=[('trulii', 'Comisión Trulii'), ('iva', 'IVA'), ('payu_fee_percentage', 'Comisión PayU porcentual'), ('payu_fee_fixed', 'Comisión PayU fija'), ('renta', 'Descuento de Retención Renta'), ('ica', 'Descuento de Retención ICA'), ('iva_trulii_payu', 'Comisión PayU IVA Trulii'), ('reteica_num', 'Reteica Numerador'), ('reteica_den', 'Reteica Denominador'), ('reteiva', 'Reteiva')], max_length=100),
        ),
    ]
