# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
