# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('sent', models.DateTimeField(null=True, verbose_name='sent')),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('cc', 'C.C.'), ('nit', 'N.I.T.'), ('ce', 'C.E.')], max_length=5)),
                ('document', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City')),
            ],
        ),
        migrations.AddField(
            model_name='organizerconfirmation',
            name='requested_signup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.RequestSignup'),
        ),
    ]
