# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveIntegerField(choices=[(2, 'Hombre'), (1, 'Mujer')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('birth_date', models.DateTimeField(null=True)),
                ('referrer_code', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.mixins.ImageOptimizable, models.Model),
        ),
    ]
