# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitycelerytaskeditactivity_calendarcelerytaskeditactivity'),
        ('students', '0002_student_verified_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='wish_list',
            field=models.ManyToManyField(through='students.WishList', to='activities.Activity'),
        ),
    ]
