# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20160304_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='wish_list',
            field=models.ManyToManyField(related_name='wishlist_students', through='students.WishList', to='activities.Activity'),
        ),
    ]
