# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160415_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='referrer_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
