# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20160426_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telephone_2',
            field=models.IntegerField(null=True),
        ),
    ]
