# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_telephone_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='telephone',
        ),
    ]
