# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='telephone_2',
            new_name='telephone',
        ),
    ]
