# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20160517_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=20),
            preserve_default=False,
        ),
    ]
