
#LEVEL CONTANTS
LEVEL_P = 'P'
LEVEL_I = 'I'
LEVEL_A = 'A'
LEVEL_N = 'N'


#ACTIVITY ORGANIZER STATUS
OPENED = 'opened'
CLOSED = 'closed'
UNPUBLISHED = 'unpublished'


#ACTIVITY STUDENT STATUS
CURRENT = 'current'
PAST = 'past'
NEXT = 'next'

#ACTIVITY SEARCH CONSTANTS
ORDER_MIN_PRICE = 'min_price'
ORDER_MAX_PRICE = 'max_price'
ORDER_SCORE = 'score'
ORDER_CLOSEST = 'closest'
