# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('level', models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado'), ('N', 'No Aplica')], max_length=1)),
                ('goals', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('audience', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('post_enroll_message', models.TextField(blank=True)),
                ('return_policy', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('youtube_video_url', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.NullBooleanField(default=False)),
                ('certification', models.NullBooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=False)),
                ('instructors', models.ManyToManyField(related_name='activities', to='organizers.Instructor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.Organizer')),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityCeleryTaskEditActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=30)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='activities')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='activities')),
                ('main_photo', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='activities.Activity')),
            ],
            bases=(utils.mixins.AssignPermissionsMixin, utils.mixins.ImageOptimizable, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_counter', models.PositiveIntegerField(default=0)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='activities.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStockPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='activities_stock')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('session_price', models.FloatField(blank=True, null=True)),
                ('enroll_open', models.BooleanField(default=True)),
                ('is_weekend', models.NullBooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('available_capacity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('schedules', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='activities.Activity')),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CalendarCeleryTaskEditActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=30)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.Calendar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Mes(es)'), (2, 'Clase(s)')])),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='activities.Calendar')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True)),
                ('headline', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, upload_to='categories/')),
                ('content_photo', models.ImageField(blank=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('occurrences', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='activitystockphoto',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.SubCategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activities.SubCategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(to='activities.Tags'),
        ),
    ]
