# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCeleryTaskEditActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=30)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarCeleryTaskEditActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=30)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.Calendar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
