# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitycelerytaskeditactivity_calendarcelerytaskeditactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
