# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='available_capacity',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
