# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 17, 0, 22, 916919, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
