# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_calendar_available_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='capacity',
        ),
    ]
