# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 14:44
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_category_seo_data'),
    ]

    operations = [
        UnaccentExtension(),
    ]
