# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activityphoto_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_date',
            field=models.DateTimeField(null=True),
        ),
    ]
