# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
