# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activitystats'),
        ('activities', '0005_remove_calendar_capacity'),
    ]

    operations = [
    ]
