# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
