# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20160607_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content_photo',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
