# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20160721_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
