# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20160817_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='closing_sale',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='enroll_open',
            field=models.BooleanField(default=True),
        ),
    ]
