# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20160829_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsession',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='number_of_sessions',
        ),
        migrations.AddField(
            model_name='calendar',
            name='schedules',
            field=models.TextField(default='Horarios'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CalendarSession',
        ),
    ]
