# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_auto_20160829_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
