# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_activity_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='calendar',
            name='session_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarpackage',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='activities.Calendar'),
        ),
    ]
