# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20160906_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='initial_date',
            field=models.DateField(),
        ),
    ]
