# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20160909_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='post_enroll_message',
            field=models.TextField(blank=True),
        ),
    ]
