# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_activity_post_enroll_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarpackage',
            name='name',
        ),
        migrations.AddField(
            model_name='calendarpackage',
            name='type',
            field=models.CharField(blank=True, choices=[(1, 'Mes(es)'), (2, 'Clase(s)')], max_length=255),
        ),
    ]
