# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_category_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='headline',
            field=models.TextField(blank=True),
        ),
    ]
