# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_auto_20160917_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarpackage',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Mes(es)'), (2, 'Clase(s)')], max_length=255),
        ),
    ]
