# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_auto_20160918_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarpackage',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Mes(es)'), (2, 'Clase(s)')]),
        ),
    ]
