# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_auto_20160919_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.TextField(),
        ),
    ]
