# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foto')),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('youtube_video_url', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('headline', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(utils.mixins.ImageOptimizable, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizerBankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=255)),
                ('bank', models.CharField(choices=[('agrario', 'BANCO AGRARIO'), ('av_villas', 'BANCO AV VILLAS'), ('bbva_colombia', 'BANCO BBVA S.A.'), ('caja_social', 'BANCO CAJA SOCIAL'), ('colpatria', 'BANCO COLPATRIA'), ('cooperativo_coopcentral', 'BANCO COOPERATIVO COOPCENTRAL'), ('corpbanca', 'BANCO CORPBANCA S.A.'), ('davivienda', 'BANCO DAVIVIENDA'), ('bogota', 'BANCO DE BOGOTÁ'), ('occidente', 'BANCO DE OCCIDENTE'), ('falabella', 'BANCO FALABELLA'), ('gnb_sudameris', 'BANCO GNB SUDAMERIS'), ('pichincha', 'BANCO PICHINCHA S.A.'), ('popular', 'BANCO POPULAR'), ('procredit', 'BANCO PROCREDIT'), ('bancolombia', 'BANCOLOMBIA'), ('bancoomeva', 'BANCOOMEVA S.A.'), ('citibank', 'CITIBANK'), ('helmbank', 'HELM BANK S.A.')], max_length=30)),
                ('document_type', models.CharField(choices=[('cc', 'Cédula de ciudadanía'), ('ce', 'Cédula de extranjería'), ('nit', 'NIT'), ('pp', 'Pasaporte'), ('de', 'Documento de identificación extranjero')], max_length=5)),
                ('document', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ahorros', 'Cuenta de ahorros'), ('corriente', 'Cuenta corriente')], max_length=10)),
                ('account', models.CharField(max_length=255)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info', to='organizers.Organizer')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='organizers.Organizer'),
        ),
    ]
