# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='verified_email',
            field=models.BooleanField(default=True),
        ),
    ]
