# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_organizer_verified_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='photo',
        ),
    ]
