# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_remove_instructor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerbankinfo',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizerbankinfo',
            name='regimen',
            field=models.CharField(blank=True, choices=[(1, 'Común'), (2, 'Gran Contribuyente')], max_length=20),
        ),
        migrations.AddField(
            model_name='organizerbankinfo',
            name='type_person',
            field=models.CharField(choices=[(1, 'Natural'), (2, 'Jurídica')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
