# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_auto_20160908_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerbankinfo',
            name='billing_telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
