# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0008_organizerbankinfo_regimen'),
        ('organizers', '0007_organizer_type'),
    ]

    operations = [
    ]
