# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
