# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 02:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.CharField(blank=True, max_length=480)),
                ('reply', models.CharField(blank=True, max_length=480)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.Activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='students.Student')),
            ],
            options={
                'permissions': (('report_review', 'Report review'), ('reply_review', 'Reply review'), ('read_review', 'Read review')),
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
    ]
