# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
        ('activities', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Calendar')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.Organizer')),
            ],
            options={
                'permissions': (('retrieve_message', 'Can retrieve a message'), ('delete_message', 'Can delete a message'), ('update_message', 'Can update a message')),
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizerMessageStudentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('organizer_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trulii_messages.OrganizerMessage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='organizermessage',
            name='students',
            field=models.ManyToManyField(related_name='organizer_messages', through='trulii_messages.OrganizerMessageStudentRelation', to='students.Student'),
        ),
    ]
