# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_auto_20160304_0910'),
        ('organizers', '0002_organizer_verified_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerMessageStudentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('organizer_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trulii_messages.OrganizerMessage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.AddField(
            model_name='organizermessage',
            name='students',
            field=models.ManyToManyField(related_name='organizer_messages', through='trulii_messages.OrganizerMessageStudentRelation', to='students.Student'),
        ),
    ]
