# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_last_date'),
        ('trulii_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizermessage',
            name='calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activities.Calendar'),
            preserve_default=False,
        ),
    ]
