# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trulii_messages', '0002_organizermessage_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizermessage',
            options={'permissions': (('retrieve_message', 'Can retrieve a message'),)},
        ),
    ]
