# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trulii_messages', '0003_auto_20160317_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizermessage',
            options={'permissions': (('retrieve_message', 'Can retrieve a message'), ('delete_message', 'Can delete a message'))},
        ),
    ]
