# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trulii_messages', '0005_auto_20160419_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizermessage',
            options={'permissions': (('retrieve_message', 'Can retrieve a message'), ('delete_message', 'Can delete a message'), ('update_message', 'Can update a message'))},
        ),
        migrations.AlterModelOptions(
            name='organizermessagestudentrelation',
            options={},
        ),
    ]
