# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('template_name', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=150)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('sent', 'SENT'), ('queued', 'QUEUED'), ('scheduled', 'SCHEDULED'), ('rejected', 'REJECTED'), ('invalid', 'INVALID'), ('error', 'ERROR')], default='queued', max_length=50)),
                ('reject_reason', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(max_length=50)),
                ('smtp_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
