# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtaskrecord',
            old_name='template',
            new_name='template_name',
        ),
        migrations.RemoveField(
            model_name='emailtaskrecord',
            name='send',
        ),
        migrations.AddField(
            model_name='emailtaskrecord',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emailtaskrecord',
            name='smtp_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='emailtaskrecord',
            name='status',
            field=models.CharField(choices=[('sent', 'SENT'), ('queued', 'QUEUED'), ('scheduled', 'SCHEDULED'), ('rejected', 'REJECTED'), ('invalid', 'INVALID'), ('error', 'ERROR')], default='queued', max_length=50),
        ),
        migrations.AddField(
            model_name='emailtaskrecord',
            name='subject',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtaskrecord',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='emailtaskrecord',
            name='task_id',
            field=models.CharField(max_length=50),
        ),
    ]
