# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='CeleryTask',
        ),
    ]
