# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='point',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='point',
            field=models.CharField(max_length=200),
        ),
    ]
