# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20151229_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326),
        ),
    ]
