# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
