# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_package_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
