# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160915_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee_2',
        ),
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
