# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 07:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_fee_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fee_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
