# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20160916_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
