# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20160922_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Mes(es)'), (2, 'Clase(s)')], null=True),
        ),
    ]
