# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'No Disponible'), ('withdrawn', 'Retirado'), ('requested', 'Solicitado')], default='unavailable', max_length=15),
        ),
    ]
