# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_package_quantity'),
        ('balances', '0002_auto_20160801_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancelog',
            name='calendar',
        ),
        migrations.AddField(
            model_name='balancelog',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='orders.Order'),
            preserve_default=False,
        ),
    ]
